import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { Main } from "next/document";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen relative">
        <Image src="/flowers.png" alt="" width={600} height={600} className="fixed -top-30 -right-30 -z-10 -rotate-90" />
        <Image src="/flowers.png" alt="" width={600} height={600} className="fixed -bottom-30 -left-20 -z-10" />
        <Navbar />
        <main className="flex flex-col flex-1">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
